version: '3.9'

services:
  app:
    container_name: crater_app
    build:
      args:
        user: crater-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: crater-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
    networks:
      - crater
      - proxy

  db:
    container_name: crater_db
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_USER: crater
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: crater
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - crater

  nginx:
    container_name: crater_nginx
    image: nginx:1.17-alpine
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - crater
      - proxy

  cron:
    container_name: crater_cron
    build:
      context: ./
      dockerfile: ./docker-compose/cron.dockerfile
    volumes:
      - ./:/var/www
    networks:
      - crater

volumes:
  db:

networks:
  crater:
  proxy:
    external:
      name: proxy